sudo: required
services:
  - docker

before_install:
  - docker build -t leroymendes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run leroymendes/react-test npm run test -- --coverage

after_success:
  - docker build -t leroymendes/multi-client ./client
  - docker build -t leroymendes/multi-nginx ./nginx
  - docker build -t leroymendes/multi-server ./server
  - docker build -t leroymendes/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push leroymendes/multi-client
  - docker push leroymendes/multi-nginx
  - docker push leroymendes/multi-server
  - docker push leroymendes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-144846369010"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
