sudo: required
services:
  - docker

before_install:
  - docker build -t leroymendes17/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run leroymendes17/react-test npm run test -- --coverage

after_success:
  - docker build -t leroymendes/multi-client ./client
  - docker build -t leroymendes/multi-nginx ./nginx
  - docker build -t leroymendes/multi-server ./server
  - docker build -t leroymendes/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push leroymendes/multi-client
  - docker push leroymendes/multi-nginx
  - docker push leroymendes/multi-server
  - docker push leroymendes/multi-worker

